# Generated by Django 3.1.2 on 2020-10-17 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_code', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now=True)),
                ('tags', models.CharField(max_length=100)),
                ('open_till', models.TimeField()),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('True_Flase', 'True_False'), ('Description', 'Description')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Write your questions here.', max_length=500)),
                ('q_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/')),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('correct', models.CharField(blank=True, max_length=100, null=True)),
                ('true_false', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Portal.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosen', models.CharField(blank=True, max_length=100, null=True)),
                ('true_false', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('a_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Portal.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Portal.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
