# Generated by Django 3.1.2 on 2020-10-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Portal', '0002_auto_20201014_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
