# Generated by Django 3.1.2 on 2020-10-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Portal', '0003_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
