# Generated by Django 3.1.2 on 2020-10-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Portal', '0004_auto_20201014_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='Write your questions here.', max_length=500),
        ),
    ]
