# Generated by Django 3.1.2 on 2020-10-14 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz_Portal', '0005_auto_20201014_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosen', models.CharField(max_length=100)),
                ('true_false', models.BooleanField()),
                ('description', models.TextField(max_length=1000)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Portal.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
