# Generated by Django 3.1.2 on 2020-10-14 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Portal', '0008_auto_20201014_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz_Portal.question'),
        ),
    ]
